apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  creationTimestamp: null
  name: carts-db
spec:
  gateways:
  - public-gateway.istio-system
  - mesh
  hosts:
  - carts-db.sockshop4-production.20.241.242.170.nip.io
  - carts-db
  http:
  - route:
    - destination:
        host: carts-db.sockshop4-production.svc.cluster.local
